all:
  children:
    routers:
      hosts:
        r1:
          ansible_host: 10.125.100.229
          ansible_user: student
          ansible_password: pass
          ansible_connection: ansible.netcommon.netconf